name: Announcement
version: 1.0.0
description: Simple announcement plugin
author: spy
main: com.spy.announcement.AnnouncementPlugin
api-version: 1.21

commands:
  announcements:
    description: Send an announcement to all players
    usage: /announcements <message>
    aliases: [announce, brodcast, broadcast]
    permission: announcement.use

permissions:
  announcement.use:
    description: Allows sending announcements
    default: op
